# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BoldWeatherApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BoldWeatherApp
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'Alamofire'

  target 'BoldWeatherAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxSwift'
    pod 'RxCocoa'
    pod 'Alamofire'
  end

  target 'BoldWeatherAppUITests' do
    # Pods for testing
  end

end
